name: API Scan workflow

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    name: API Scan
    steps:
      - uses: actions/checkout@v2
      - uses: zaproxy/action-api-scan@v0.4.0
        with:
          target: openapi.json
